//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.PersonaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", ConfigurationName="PersonaWS.PersonaWS")]
    public interface PersonaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/calcularLimitePrestamosReque" +
            "st", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/calcularLimitePrestamosRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.PersonaWS.calcularLimitePrestamosResponse calcularLimitePrestamos(FrontEnd.PersonaWS.calcularLimitePrestamosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/calcularLimitePrestamosReque" +
            "st", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/calcularLimitePrestamosRespo" +
            "nse")]
        System.Threading.Tasks.Task<FrontEnd.PersonaWS.calcularLimitePrestamosResponse> calcularLimitePrestamosAsync(FrontEnd.PersonaWS.calcularLimitePrestamosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/obtenerPersonaRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/obtenerPersonaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.PersonaWS.obtenerPersonaResponse obtenerPersona(FrontEnd.PersonaWS.obtenerPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/obtenerPersonaRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/obtenerPersonaResponse")]
        System.Threading.Tasks.Task<FrontEnd.PersonaWS.obtenerPersonaResponse> obtenerPersonaAsync(FrontEnd.PersonaWS.obtenerPersonaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/insertarPersonaRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/insertarPersonaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.PersonaWS.insertarPersonaResponse insertarPersona(FrontEnd.PersonaWS.insertarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/insertarPersonaRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/insertarPersonaResponse")]
        System.Threading.Tasks.Task<FrontEnd.PersonaWS.insertarPersonaResponse> insertarPersonaAsync(FrontEnd.PersonaWS.insertarPersonaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/modificarPersonaRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/modificarPersonaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.PersonaWS.modificarPersonaResponse modificarPersona(FrontEnd.PersonaWS.modificarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/modificarPersonaRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/modificarPersonaResponse")]
        System.Threading.Tasks.Task<FrontEnd.PersonaWS.modificarPersonaResponse> modificarPersonaAsync(FrontEnd.PersonaWS.modificarPersonaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/eliminarPersonaRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/eliminarPersonaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.PersonaWS.eliminarPersonaResponse eliminarPersona(FrontEnd.PersonaWS.eliminarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/eliminarPersonaRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/eliminarPersonaResponse")]
        System.Threading.Tasks.Task<FrontEnd.PersonaWS.eliminarPersonaResponse> eliminarPersonaAsync(FrontEnd.PersonaWS.eliminarPersonaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/listarPersonasRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/listarPersonasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.PersonaWS.listarPersonasResponse listarPersonas(FrontEnd.PersonaWS.listarPersonasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/listarPersonasRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/listarPersonasResponse")]
        System.Threading.Tasks.Task<FrontEnd.PersonaWS.listarPersonasResponse> listarPersonasAsync(FrontEnd.PersonaWS.listarPersonasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/modificarContrasenhaRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/modificarContrasenhaResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.PersonaWS.modificarContrasenhaResponse modificarContrasenha(FrontEnd.PersonaWS.modificarContrasenhaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/modificarContrasenhaRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/modificarContrasenhaResponse" +
            "")]
        System.Threading.Tasks.Task<FrontEnd.PersonaWS.modificarContrasenhaResponse> modificarContrasenhaAsync(FrontEnd.PersonaWS.modificarContrasenhaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/obtenerPersonaPorCredenciale" +
            "sRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/obtenerPersonaPorCredenciale" +
            "sResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.PersonaWS.obtenerPersonaPorCredencialesResponse obtenerPersonaPorCredenciales(FrontEnd.PersonaWS.obtenerPersonaPorCredencialesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/obtenerPersonaPorCredenciale" +
            "sRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/obtenerPersonaPorCredenciale" +
            "sResponse")]
        System.Threading.Tasks.Task<FrontEnd.PersonaWS.obtenerPersonaPorCredencialesResponse> obtenerPersonaPorCredencialesAsync(FrontEnd.PersonaWS.obtenerPersonaPorCredencialesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/contarPersonasRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/contarPersonasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.PersonaWS.contarPersonasResponse contarPersonas(FrontEnd.PersonaWS.contarPersonasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/contarPersonasRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/contarPersonasResponse")]
        System.Threading.Tasks.Task<FrontEnd.PersonaWS.contarPersonasResponse> contarPersonasAsync(FrontEnd.PersonaWS.contarPersonasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/listarPersonasPaginadoReques" +
            "t", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/listarPersonasPaginadoRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.PersonaWS.listarPersonasPaginadoResponse listarPersonasPaginado(FrontEnd.PersonaWS.listarPersonasPaginadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/listarPersonasPaginadoReques" +
            "t", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PersonaWS/listarPersonasPaginadoRespon" +
            "se")]
        System.Threading.Tasks.Task<FrontEnd.PersonaWS.listarPersonasPaginadoResponse> listarPersonasPaginadoAsync(FrontEnd.PersonaWS.listarPersonasPaginadoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="calcularLimitePrestamos", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class calcularLimitePrestamosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigo;
        
        public calcularLimitePrestamosRequest() {
        }
        
        public calcularLimitePrestamosRequest(string codigo) {
            this.codigo = codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="calcularLimitePrestamosResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class calcularLimitePrestamosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public calcularLimitePrestamosResponse() {
        }
        
        public calcularLimitePrestamosResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class personasDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string contrasenhaField;
        
        private string correoField;
        
        private double deudaField;
        
        private bool deudaFieldSpecified;
        
        private string direccionField;
        
        private System.DateTime fechaContratoFinalField;
        
        private bool fechaContratoFinalFieldSpecified;
        
        private System.DateTime fechaContratoInicioField;
        
        private bool fechaContratoInicioFieldSpecified;
        
        private System.DateTime fechaSancionFinalField;
        
        private bool fechaSancionFinalFieldSpecified;
        
        private int idPersonaField;
        
        private bool idPersonaFieldSpecified;
        
        private string maternoField;
        
        private nivelesInglesDTO nivelField;
        
        private string nombreField;
        
        private string paternoField;
        
        private sedesDTO sedeField;
        
        private string telefonoField;
        
        private tipoPersona tipoField;
        
        private bool tipoFieldSpecified;
        
        private turnos turnoField;
        
        private bool turnoFieldSpecified;
        
        private bool vigenteField;
        
        private bool vigenteFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contrasenha {
            get {
                return this.contrasenhaField;
            }
            set {
                this.contrasenhaField = value;
                this.RaisePropertyChanged("contrasenha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double deuda {
            get {
                return this.deudaField;
            }
            set {
                this.deudaField = value;
                this.RaisePropertyChanged("deuda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deudaSpecified {
            get {
                return this.deudaFieldSpecified;
            }
            set {
                this.deudaFieldSpecified = value;
                this.RaisePropertyChanged("deudaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaContratoFinal {
            get {
                return this.fechaContratoFinalField;
            }
            set {
                this.fechaContratoFinalField = value;
                this.RaisePropertyChanged("fechaContratoFinal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaContratoFinalSpecified {
            get {
                return this.fechaContratoFinalFieldSpecified;
            }
            set {
                this.fechaContratoFinalFieldSpecified = value;
                this.RaisePropertyChanged("fechaContratoFinalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime fechaContratoInicio {
            get {
                return this.fechaContratoInicioField;
            }
            set {
                this.fechaContratoInicioField = value;
                this.RaisePropertyChanged("fechaContratoInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaContratoInicioSpecified {
            get {
                return this.fechaContratoInicioFieldSpecified;
            }
            set {
                this.fechaContratoInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaContratoInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime fechaSancionFinal {
            get {
                return this.fechaSancionFinalField;
            }
            set {
                this.fechaSancionFinalField = value;
                this.RaisePropertyChanged("fechaSancionFinal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSancionFinalSpecified {
            get {
                return this.fechaSancionFinalFieldSpecified;
            }
            set {
                this.fechaSancionFinalFieldSpecified = value;
                this.RaisePropertyChanged("fechaSancionFinalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPersonaSpecified {
            get {
                return this.idPersonaFieldSpecified;
            }
            set {
                this.idPersonaFieldSpecified = value;
                this.RaisePropertyChanged("idPersonaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string materno {
            get {
                return this.maternoField;
            }
            set {
                this.maternoField = value;
                this.RaisePropertyChanged("materno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public nivelesInglesDTO nivel {
            get {
                return this.nivelField;
            }
            set {
                this.nivelField = value;
                this.RaisePropertyChanged("nivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string paterno {
            get {
                return this.paternoField;
            }
            set {
                this.paternoField = value;
                this.RaisePropertyChanged("paterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public sedesDTO sede {
            get {
                return this.sedeField;
            }
            set {
                this.sedeField = value;
                this.RaisePropertyChanged("sede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public tipoPersona tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public turnos turno {
            get {
                return this.turnoField;
            }
            set {
                this.turnoField = value;
                this.RaisePropertyChanged("turno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool turnoSpecified {
            get {
                return this.turnoFieldSpecified;
            }
            set {
                this.turnoFieldSpecified = value;
                this.RaisePropertyChanged("turnoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public bool vigente {
            get {
                return this.vigenteField;
            }
            set {
                this.vigenteField = value;
                this.RaisePropertyChanged("vigente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vigenteSpecified {
            get {
                return this.vigenteFieldSpecified;
            }
            set {
                this.vigenteFieldSpecified = value;
                this.RaisePropertyChanged("vigenteSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class nivelesInglesDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idNivelField;
        
        private nivel nivelField;
        
        private bool nivelFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idNivel {
            get {
                return this.idNivelField;
            }
            set {
                this.idNivelField = value;
                this.RaisePropertyChanged("idNivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public nivel nivel {
            get {
                return this.nivelField;
            }
            set {
                this.nivelField = value;
                this.RaisePropertyChanged("nivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nivelSpecified {
            get {
                return this.nivelFieldSpecified;
            }
            set {
                this.nivelFieldSpecified = value;
                this.RaisePropertyChanged("nivelSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public enum nivel {
        
        /// <remarks/>
        BASICO,
        
        /// <remarks/>
        INTERMEDIO,
        
        /// <remarks/>
        AVANZADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class sedesDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activaField;
        
        private bool activaFieldSpecified;
        
        private string correoContactoField;
        
        private string direccionField;
        
        private string distritoField;
        
        private int idSedeField;
        
        private bool idSedeFieldSpecified;
        
        private string nombreField;
        
        private string telefonoContactoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
                this.RaisePropertyChanged("activa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activaSpecified {
            get {
                return this.activaFieldSpecified;
            }
            set {
                this.activaFieldSpecified = value;
                this.RaisePropertyChanged("activaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correoContacto {
            get {
                return this.correoContactoField;
            }
            set {
                this.correoContactoField = value;
                this.RaisePropertyChanged("correoContacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string distrito {
            get {
                return this.distritoField;
            }
            set {
                this.distritoField = value;
                this.RaisePropertyChanged("distrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idSede {
            get {
                return this.idSedeField;
            }
            set {
                this.idSedeField = value;
                this.RaisePropertyChanged("idSede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSedeSpecified {
            get {
                return this.idSedeFieldSpecified;
            }
            set {
                this.idSedeFieldSpecified = value;
                this.RaisePropertyChanged("idSedeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string telefonoContacto {
            get {
                return this.telefonoContactoField;
            }
            set {
                this.telefonoContactoField = value;
                this.RaisePropertyChanged("telefonoContacto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public enum tipoPersona {
        
        /// <remarks/>
        PROFESOR,
        
        /// <remarks/>
        ADMINISTRADOR,
        
        /// <remarks/>
        ESTUDIANTE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public enum turnos {
        
        /// <remarks/>
        MANHANA,
        
        /// <remarks/>
        TARDE,
        
        /// <remarks/>
        NOCHE,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPersona", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class obtenerPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPersona;
        
        public obtenerPersonaRequest() {
        }
        
        public obtenerPersonaRequest(int idPersona) {
            this.idPersona = idPersona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPersonaResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class obtenerPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontEnd.PersonaWS.personasDTO @return;
        
        public obtenerPersonaResponse() {
        }
        
        public obtenerPersonaResponse(FrontEnd.PersonaWS.personasDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPersona", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class insertarPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string paterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string materno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasenha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontEnd.PersonaWS.tipoPersona tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontEnd.PersonaWS.turnos turno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaContratoInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaContratoFinal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double deuda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaSancionFinal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=14)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool vigente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=15)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idNivel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=16)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idSede;
        
        public insertarPersonaRequest() {
        }
        
        public insertarPersonaRequest(
                    string codigo, 
                    string nombre, 
                    string paterno, 
                    string materno, 
                    string direccion, 
                    string telefono, 
                    string correo, 
                    string contrasenha, 
                    FrontEnd.PersonaWS.tipoPersona tipo, 
                    FrontEnd.PersonaWS.turnos turno, 
                    System.DateTime fechaContratoInicio, 
                    System.DateTime fechaContratoFinal, 
                    double deuda, 
                    System.DateTime fechaSancionFinal, 
                    bool vigente, 
                    int idNivel, 
                    int idSede) {
            this.codigo = codigo;
            this.nombre = nombre;
            this.paterno = paterno;
            this.materno = materno;
            this.direccion = direccion;
            this.telefono = telefono;
            this.correo = correo;
            this.contrasenha = contrasenha;
            this.tipo = tipo;
            this.turno = turno;
            this.fechaContratoInicio = fechaContratoInicio;
            this.fechaContratoFinal = fechaContratoFinal;
            this.deuda = deuda;
            this.fechaSancionFinal = fechaSancionFinal;
            this.vigente = vigente;
            this.idNivel = idNivel;
            this.idSede = idSede;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPersonaResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class insertarPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarPersonaResponse() {
        }
        
        public insertarPersonaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPersona", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class modificarPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPersona;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string paterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string materno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasenha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontEnd.PersonaWS.tipoPersona tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontEnd.PersonaWS.turnos turno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaContratoInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaContratoFinal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double deuda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=14)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaSancionFinal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=15)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool vigente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=16)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idNivel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=17)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idSede;
        
        public modificarPersonaRequest() {
        }
        
        public modificarPersonaRequest(
                    int idPersona, 
                    string codigo, 
                    string nombre, 
                    string paterno, 
                    string materno, 
                    string direccion, 
                    string telefono, 
                    string correo, 
                    string contrasenha, 
                    FrontEnd.PersonaWS.tipoPersona tipo, 
                    FrontEnd.PersonaWS.turnos turno, 
                    System.DateTime fechaContratoInicio, 
                    System.DateTime fechaContratoFinal, 
                    double deuda, 
                    System.DateTime fechaSancionFinal, 
                    bool vigente, 
                    int idNivel, 
                    int idSede) {
            this.idPersona = idPersona;
            this.codigo = codigo;
            this.nombre = nombre;
            this.paterno = paterno;
            this.materno = materno;
            this.direccion = direccion;
            this.telefono = telefono;
            this.correo = correo;
            this.contrasenha = contrasenha;
            this.tipo = tipo;
            this.turno = turno;
            this.fechaContratoInicio = fechaContratoInicio;
            this.fechaContratoFinal = fechaContratoFinal;
            this.deuda = deuda;
            this.fechaSancionFinal = fechaSancionFinal;
            this.vigente = vigente;
            this.idNivel = idNivel;
            this.idSede = idSede;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPersonaResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class modificarPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarPersonaResponse() {
        }
        
        public modificarPersonaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPersona", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class eliminarPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPersona;
        
        public eliminarPersonaRequest() {
        }
        
        public eliminarPersonaRequest(int idPersona) {
            this.idPersona = idPersona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPersonaResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class eliminarPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarPersonaResponse() {
        }
        
        public eliminarPersonaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPersonas", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarPersonasRequest {
        
        public listarPersonasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPersonasResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarPersonasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontEnd.PersonaWS.personasDTO[] @return;
        
        public listarPersonasResponse() {
        }
        
        public listarPersonasResponse(FrontEnd.PersonaWS.personasDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarContrasenha", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class modificarContrasenhaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPersona;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nuevaContrasenha;
        
        public modificarContrasenhaRequest() {
        }
        
        public modificarContrasenhaRequest(int idPersona, string nuevaContrasenha) {
            this.idPersona = idPersona;
            this.nuevaContrasenha = nuevaContrasenha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarContrasenhaResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class modificarContrasenhaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarContrasenhaResponse() {
        }
        
        public modificarContrasenhaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPersonaPorCredenciales", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class obtenerPersonaPorCredencialesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo_codigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasenha;
        
        public obtenerPersonaPorCredencialesRequest() {
        }
        
        public obtenerPersonaPorCredencialesRequest(string correo_codigo, string contrasenha) {
            this.correo_codigo = correo_codigo;
            this.contrasenha = contrasenha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPersonaPorCredencialesResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class obtenerPersonaPorCredencialesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontEnd.PersonaWS.personasDTO @return;
        
        public obtenerPersonaPorCredencialesResponse() {
        }
        
        public obtenerPersonaPorCredencialesResponse(FrontEnd.PersonaWS.personasDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="contarPersonas", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class contarPersonasRequest {
        
        public contarPersonasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="contarPersonasResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class contarPersonasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public contarPersonasResponse() {
        }
        
        public contarPersonasResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPersonasPaginado", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarPersonasPaginadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int limite;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pagina;
        
        public listarPersonasPaginadoRequest() {
        }
        
        public listarPersonasPaginadoRequest(int limite, int pagina) {
            this.limite = limite;
            this.pagina = pagina;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPersonasPaginadoResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarPersonasPaginadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontEnd.PersonaWS.personasDTO[] @return;
        
        public listarPersonasPaginadoResponse() {
        }
        
        public listarPersonasPaginadoResponse(FrontEnd.PersonaWS.personasDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PersonaWSChannel : FrontEnd.PersonaWS.PersonaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonaWSClient : System.ServiceModel.ClientBase<FrontEnd.PersonaWS.PersonaWS>, FrontEnd.PersonaWS.PersonaWS {
        
        public PersonaWSClient() {
        }
        
        public PersonaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.PersonaWS.calcularLimitePrestamosResponse FrontEnd.PersonaWS.PersonaWS.calcularLimitePrestamos(FrontEnd.PersonaWS.calcularLimitePrestamosRequest request) {
            return base.Channel.calcularLimitePrestamos(request);
        }
        
        public int calcularLimitePrestamos(string codigo) {
            FrontEnd.PersonaWS.calcularLimitePrestamosRequest inValue = new FrontEnd.PersonaWS.calcularLimitePrestamosRequest();
            inValue.codigo = codigo;
            FrontEnd.PersonaWS.calcularLimitePrestamosResponse retVal = ((FrontEnd.PersonaWS.PersonaWS)(this)).calcularLimitePrestamos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.PersonaWS.calcularLimitePrestamosResponse> FrontEnd.PersonaWS.PersonaWS.calcularLimitePrestamosAsync(FrontEnd.PersonaWS.calcularLimitePrestamosRequest request) {
            return base.Channel.calcularLimitePrestamosAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.PersonaWS.calcularLimitePrestamosResponse> calcularLimitePrestamosAsync(string codigo) {
            FrontEnd.PersonaWS.calcularLimitePrestamosRequest inValue = new FrontEnd.PersonaWS.calcularLimitePrestamosRequest();
            inValue.codigo = codigo;
            return ((FrontEnd.PersonaWS.PersonaWS)(this)).calcularLimitePrestamosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.PersonaWS.obtenerPersonaResponse FrontEnd.PersonaWS.PersonaWS.obtenerPersona(FrontEnd.PersonaWS.obtenerPersonaRequest request) {
            return base.Channel.obtenerPersona(request);
        }
        
        public FrontEnd.PersonaWS.personasDTO obtenerPersona(int idPersona) {
            FrontEnd.PersonaWS.obtenerPersonaRequest inValue = new FrontEnd.PersonaWS.obtenerPersonaRequest();
            inValue.idPersona = idPersona;
            FrontEnd.PersonaWS.obtenerPersonaResponse retVal = ((FrontEnd.PersonaWS.PersonaWS)(this)).obtenerPersona(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.PersonaWS.obtenerPersonaResponse> FrontEnd.PersonaWS.PersonaWS.obtenerPersonaAsync(FrontEnd.PersonaWS.obtenerPersonaRequest request) {
            return base.Channel.obtenerPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.PersonaWS.obtenerPersonaResponse> obtenerPersonaAsync(int idPersona) {
            FrontEnd.PersonaWS.obtenerPersonaRequest inValue = new FrontEnd.PersonaWS.obtenerPersonaRequest();
            inValue.idPersona = idPersona;
            return ((FrontEnd.PersonaWS.PersonaWS)(this)).obtenerPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.PersonaWS.insertarPersonaResponse FrontEnd.PersonaWS.PersonaWS.insertarPersona(FrontEnd.PersonaWS.insertarPersonaRequest request) {
            return base.Channel.insertarPersona(request);
        }
        
        public int insertarPersona(
                    string codigo, 
                    string nombre, 
                    string paterno, 
                    string materno, 
                    string direccion, 
                    string telefono, 
                    string correo, 
                    string contrasenha, 
                    FrontEnd.PersonaWS.tipoPersona tipo, 
                    FrontEnd.PersonaWS.turnos turno, 
                    System.DateTime fechaContratoInicio, 
                    System.DateTime fechaContratoFinal, 
                    double deuda, 
                    System.DateTime fechaSancionFinal, 
                    bool vigente, 
                    int idNivel, 
                    int idSede) {
            FrontEnd.PersonaWS.insertarPersonaRequest inValue = new FrontEnd.PersonaWS.insertarPersonaRequest();
            inValue.codigo = codigo;
            inValue.nombre = nombre;
            inValue.paterno = paterno;
            inValue.materno = materno;
            inValue.direccion = direccion;
            inValue.telefono = telefono;
            inValue.correo = correo;
            inValue.contrasenha = contrasenha;
            inValue.tipo = tipo;
            inValue.turno = turno;
            inValue.fechaContratoInicio = fechaContratoInicio;
            inValue.fechaContratoFinal = fechaContratoFinal;
            inValue.deuda = deuda;
            inValue.fechaSancionFinal = fechaSancionFinal;
            inValue.vigente = vigente;
            inValue.idNivel = idNivel;
            inValue.idSede = idSede;
            FrontEnd.PersonaWS.insertarPersonaResponse retVal = ((FrontEnd.PersonaWS.PersonaWS)(this)).insertarPersona(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.PersonaWS.insertarPersonaResponse> FrontEnd.PersonaWS.PersonaWS.insertarPersonaAsync(FrontEnd.PersonaWS.insertarPersonaRequest request) {
            return base.Channel.insertarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.PersonaWS.insertarPersonaResponse> insertarPersonaAsync(
                    string codigo, 
                    string nombre, 
                    string paterno, 
                    string materno, 
                    string direccion, 
                    string telefono, 
                    string correo, 
                    string contrasenha, 
                    FrontEnd.PersonaWS.tipoPersona tipo, 
                    FrontEnd.PersonaWS.turnos turno, 
                    System.DateTime fechaContratoInicio, 
                    System.DateTime fechaContratoFinal, 
                    double deuda, 
                    System.DateTime fechaSancionFinal, 
                    bool vigente, 
                    int idNivel, 
                    int idSede) {
            FrontEnd.PersonaWS.insertarPersonaRequest inValue = new FrontEnd.PersonaWS.insertarPersonaRequest();
            inValue.codigo = codigo;
            inValue.nombre = nombre;
            inValue.paterno = paterno;
            inValue.materno = materno;
            inValue.direccion = direccion;
            inValue.telefono = telefono;
            inValue.correo = correo;
            inValue.contrasenha = contrasenha;
            inValue.tipo = tipo;
            inValue.turno = turno;
            inValue.fechaContratoInicio = fechaContratoInicio;
            inValue.fechaContratoFinal = fechaContratoFinal;
            inValue.deuda = deuda;
            inValue.fechaSancionFinal = fechaSancionFinal;
            inValue.vigente = vigente;
            inValue.idNivel = idNivel;
            inValue.idSede = idSede;
            return ((FrontEnd.PersonaWS.PersonaWS)(this)).insertarPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.PersonaWS.modificarPersonaResponse FrontEnd.PersonaWS.PersonaWS.modificarPersona(FrontEnd.PersonaWS.modificarPersonaRequest request) {
            return base.Channel.modificarPersona(request);
        }
        
        public int modificarPersona(
                    int idPersona, 
                    string codigo, 
                    string nombre, 
                    string paterno, 
                    string materno, 
                    string direccion, 
                    string telefono, 
                    string correo, 
                    string contrasenha, 
                    FrontEnd.PersonaWS.tipoPersona tipo, 
                    FrontEnd.PersonaWS.turnos turno, 
                    System.DateTime fechaContratoInicio, 
                    System.DateTime fechaContratoFinal, 
                    double deuda, 
                    System.DateTime fechaSancionFinal, 
                    bool vigente, 
                    int idNivel, 
                    int idSede) {
            FrontEnd.PersonaWS.modificarPersonaRequest inValue = new FrontEnd.PersonaWS.modificarPersonaRequest();
            inValue.idPersona = idPersona;
            inValue.codigo = codigo;
            inValue.nombre = nombre;
            inValue.paterno = paterno;
            inValue.materno = materno;
            inValue.direccion = direccion;
            inValue.telefono = telefono;
            inValue.correo = correo;
            inValue.contrasenha = contrasenha;
            inValue.tipo = tipo;
            inValue.turno = turno;
            inValue.fechaContratoInicio = fechaContratoInicio;
            inValue.fechaContratoFinal = fechaContratoFinal;
            inValue.deuda = deuda;
            inValue.fechaSancionFinal = fechaSancionFinal;
            inValue.vigente = vigente;
            inValue.idNivel = idNivel;
            inValue.idSede = idSede;
            FrontEnd.PersonaWS.modificarPersonaResponse retVal = ((FrontEnd.PersonaWS.PersonaWS)(this)).modificarPersona(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.PersonaWS.modificarPersonaResponse> FrontEnd.PersonaWS.PersonaWS.modificarPersonaAsync(FrontEnd.PersonaWS.modificarPersonaRequest request) {
            return base.Channel.modificarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.PersonaWS.modificarPersonaResponse> modificarPersonaAsync(
                    int idPersona, 
                    string codigo, 
                    string nombre, 
                    string paterno, 
                    string materno, 
                    string direccion, 
                    string telefono, 
                    string correo, 
                    string contrasenha, 
                    FrontEnd.PersonaWS.tipoPersona tipo, 
                    FrontEnd.PersonaWS.turnos turno, 
                    System.DateTime fechaContratoInicio, 
                    System.DateTime fechaContratoFinal, 
                    double deuda, 
                    System.DateTime fechaSancionFinal, 
                    bool vigente, 
                    int idNivel, 
                    int idSede) {
            FrontEnd.PersonaWS.modificarPersonaRequest inValue = new FrontEnd.PersonaWS.modificarPersonaRequest();
            inValue.idPersona = idPersona;
            inValue.codigo = codigo;
            inValue.nombre = nombre;
            inValue.paterno = paterno;
            inValue.materno = materno;
            inValue.direccion = direccion;
            inValue.telefono = telefono;
            inValue.correo = correo;
            inValue.contrasenha = contrasenha;
            inValue.tipo = tipo;
            inValue.turno = turno;
            inValue.fechaContratoInicio = fechaContratoInicio;
            inValue.fechaContratoFinal = fechaContratoFinal;
            inValue.deuda = deuda;
            inValue.fechaSancionFinal = fechaSancionFinal;
            inValue.vigente = vigente;
            inValue.idNivel = idNivel;
            inValue.idSede = idSede;
            return ((FrontEnd.PersonaWS.PersonaWS)(this)).modificarPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.PersonaWS.eliminarPersonaResponse FrontEnd.PersonaWS.PersonaWS.eliminarPersona(FrontEnd.PersonaWS.eliminarPersonaRequest request) {
            return base.Channel.eliminarPersona(request);
        }
        
        public int eliminarPersona(int idPersona) {
            FrontEnd.PersonaWS.eliminarPersonaRequest inValue = new FrontEnd.PersonaWS.eliminarPersonaRequest();
            inValue.idPersona = idPersona;
            FrontEnd.PersonaWS.eliminarPersonaResponse retVal = ((FrontEnd.PersonaWS.PersonaWS)(this)).eliminarPersona(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.PersonaWS.eliminarPersonaResponse> FrontEnd.PersonaWS.PersonaWS.eliminarPersonaAsync(FrontEnd.PersonaWS.eliminarPersonaRequest request) {
            return base.Channel.eliminarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.PersonaWS.eliminarPersonaResponse> eliminarPersonaAsync(int idPersona) {
            FrontEnd.PersonaWS.eliminarPersonaRequest inValue = new FrontEnd.PersonaWS.eliminarPersonaRequest();
            inValue.idPersona = idPersona;
            return ((FrontEnd.PersonaWS.PersonaWS)(this)).eliminarPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.PersonaWS.listarPersonasResponse FrontEnd.PersonaWS.PersonaWS.listarPersonas(FrontEnd.PersonaWS.listarPersonasRequest request) {
            return base.Channel.listarPersonas(request);
        }
        
        public FrontEnd.PersonaWS.personasDTO[] listarPersonas() {
            FrontEnd.PersonaWS.listarPersonasRequest inValue = new FrontEnd.PersonaWS.listarPersonasRequest();
            FrontEnd.PersonaWS.listarPersonasResponse retVal = ((FrontEnd.PersonaWS.PersonaWS)(this)).listarPersonas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.PersonaWS.listarPersonasResponse> FrontEnd.PersonaWS.PersonaWS.listarPersonasAsync(FrontEnd.PersonaWS.listarPersonasRequest request) {
            return base.Channel.listarPersonasAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.PersonaWS.listarPersonasResponse> listarPersonasAsync() {
            FrontEnd.PersonaWS.listarPersonasRequest inValue = new FrontEnd.PersonaWS.listarPersonasRequest();
            return ((FrontEnd.PersonaWS.PersonaWS)(this)).listarPersonasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.PersonaWS.modificarContrasenhaResponse FrontEnd.PersonaWS.PersonaWS.modificarContrasenha(FrontEnd.PersonaWS.modificarContrasenhaRequest request) {
            return base.Channel.modificarContrasenha(request);
        }
        
        public int modificarContrasenha(int idPersona, string nuevaContrasenha) {
            FrontEnd.PersonaWS.modificarContrasenhaRequest inValue = new FrontEnd.PersonaWS.modificarContrasenhaRequest();
            inValue.idPersona = idPersona;
            inValue.nuevaContrasenha = nuevaContrasenha;
            FrontEnd.PersonaWS.modificarContrasenhaResponse retVal = ((FrontEnd.PersonaWS.PersonaWS)(this)).modificarContrasenha(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.PersonaWS.modificarContrasenhaResponse> FrontEnd.PersonaWS.PersonaWS.modificarContrasenhaAsync(FrontEnd.PersonaWS.modificarContrasenhaRequest request) {
            return base.Channel.modificarContrasenhaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.PersonaWS.modificarContrasenhaResponse> modificarContrasenhaAsync(int idPersona, string nuevaContrasenha) {
            FrontEnd.PersonaWS.modificarContrasenhaRequest inValue = new FrontEnd.PersonaWS.modificarContrasenhaRequest();
            inValue.idPersona = idPersona;
            inValue.nuevaContrasenha = nuevaContrasenha;
            return ((FrontEnd.PersonaWS.PersonaWS)(this)).modificarContrasenhaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.PersonaWS.obtenerPersonaPorCredencialesResponse FrontEnd.PersonaWS.PersonaWS.obtenerPersonaPorCredenciales(FrontEnd.PersonaWS.obtenerPersonaPorCredencialesRequest request) {
            return base.Channel.obtenerPersonaPorCredenciales(request);
        }
        
        public FrontEnd.PersonaWS.personasDTO obtenerPersonaPorCredenciales(string correo_codigo, string contrasenha) {
            FrontEnd.PersonaWS.obtenerPersonaPorCredencialesRequest inValue = new FrontEnd.PersonaWS.obtenerPersonaPorCredencialesRequest();
            inValue.correo_codigo = correo_codigo;
            inValue.contrasenha = contrasenha;
            FrontEnd.PersonaWS.obtenerPersonaPorCredencialesResponse retVal = ((FrontEnd.PersonaWS.PersonaWS)(this)).obtenerPersonaPorCredenciales(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.PersonaWS.obtenerPersonaPorCredencialesResponse> FrontEnd.PersonaWS.PersonaWS.obtenerPersonaPorCredencialesAsync(FrontEnd.PersonaWS.obtenerPersonaPorCredencialesRequest request) {
            return base.Channel.obtenerPersonaPorCredencialesAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.PersonaWS.obtenerPersonaPorCredencialesResponse> obtenerPersonaPorCredencialesAsync(string correo_codigo, string contrasenha) {
            FrontEnd.PersonaWS.obtenerPersonaPorCredencialesRequest inValue = new FrontEnd.PersonaWS.obtenerPersonaPorCredencialesRequest();
            inValue.correo_codigo = correo_codigo;
            inValue.contrasenha = contrasenha;
            return ((FrontEnd.PersonaWS.PersonaWS)(this)).obtenerPersonaPorCredencialesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.PersonaWS.contarPersonasResponse FrontEnd.PersonaWS.PersonaWS.contarPersonas(FrontEnd.PersonaWS.contarPersonasRequest request) {
            return base.Channel.contarPersonas(request);
        }
        
        public int contarPersonas() {
            FrontEnd.PersonaWS.contarPersonasRequest inValue = new FrontEnd.PersonaWS.contarPersonasRequest();
            FrontEnd.PersonaWS.contarPersonasResponse retVal = ((FrontEnd.PersonaWS.PersonaWS)(this)).contarPersonas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.PersonaWS.contarPersonasResponse> FrontEnd.PersonaWS.PersonaWS.contarPersonasAsync(FrontEnd.PersonaWS.contarPersonasRequest request) {
            return base.Channel.contarPersonasAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.PersonaWS.contarPersonasResponse> contarPersonasAsync() {
            FrontEnd.PersonaWS.contarPersonasRequest inValue = new FrontEnd.PersonaWS.contarPersonasRequest();
            return ((FrontEnd.PersonaWS.PersonaWS)(this)).contarPersonasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.PersonaWS.listarPersonasPaginadoResponse FrontEnd.PersonaWS.PersonaWS.listarPersonasPaginado(FrontEnd.PersonaWS.listarPersonasPaginadoRequest request) {
            return base.Channel.listarPersonasPaginado(request);
        }
        
        public FrontEnd.PersonaWS.personasDTO[] listarPersonasPaginado(int limite, int pagina) {
            FrontEnd.PersonaWS.listarPersonasPaginadoRequest inValue = new FrontEnd.PersonaWS.listarPersonasPaginadoRequest();
            inValue.limite = limite;
            inValue.pagina = pagina;
            FrontEnd.PersonaWS.listarPersonasPaginadoResponse retVal = ((FrontEnd.PersonaWS.PersonaWS)(this)).listarPersonasPaginado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.PersonaWS.listarPersonasPaginadoResponse> FrontEnd.PersonaWS.PersonaWS.listarPersonasPaginadoAsync(FrontEnd.PersonaWS.listarPersonasPaginadoRequest request) {
            return base.Channel.listarPersonasPaginadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.PersonaWS.listarPersonasPaginadoResponse> listarPersonasPaginadoAsync(int limite, int pagina) {
            FrontEnd.PersonaWS.listarPersonasPaginadoRequest inValue = new FrontEnd.PersonaWS.listarPersonasPaginadoRequest();
            inValue.limite = limite;
            inValue.pagina = pagina;
            return ((FrontEnd.PersonaWS.PersonaWS)(this)).listarPersonasPaginadoAsync(inValue);
        }
    }
}
