//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.PrestamoEjemplarWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", ConfigurationName="PrestamoEjemplarWS.PrestamoEjemplarWS")]
    public interface PrestamoEjemplarWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/insertarPrestamoEje" +
            "mplarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/insertarPrestamoEje" +
            "mplarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.PrestamoEjemplarWS.insertarPrestamoEjemplarResponse insertarPrestamoEjemplar(FrontEnd.PrestamoEjemplarWS.insertarPrestamoEjemplarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/insertarPrestamoEje" +
            "mplarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/insertarPrestamoEje" +
            "mplarResponse")]
        System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.insertarPrestamoEjemplarResponse> insertarPrestamoEjemplarAsync(FrontEnd.PrestamoEjemplarWS.insertarPrestamoEjemplarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosDevu" +
            "eltosRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosDevu" +
            "eltosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.PrestamoEjemplarWS.listarPrestamosDevueltosResponse listarPrestamosDevueltos(FrontEnd.PrestamoEjemplarWS.listarPrestamosDevueltosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosDevu" +
            "eltosRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosDevu" +
            "eltosResponse")]
        System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.listarPrestamosDevueltosResponse> listarPrestamosDevueltosAsync(FrontEnd.PrestamoEjemplarWS.listarPrestamosDevueltosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosAtra" +
            "sadosRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosAtra" +
            "sadosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.PrestamoEjemplarWS.listarPrestamosAtrasadosResponse listarPrestamosAtrasados(FrontEnd.PrestamoEjemplarWS.listarPrestamosAtrasadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosAtra" +
            "sadosRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosAtra" +
            "sadosResponse")]
        System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.listarPrestamosAtrasadosResponse> listarPrestamosAtrasadosAsync(FrontEnd.PrestamoEjemplarWS.listarPrestamosAtrasadosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/modificarPrestamoEj" +
            "emplarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/modificarPrestamoEj" +
            "emplarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.PrestamoEjemplarWS.modificarPrestamoEjemplarResponse modificarPrestamoEjemplar(FrontEnd.PrestamoEjemplarWS.modificarPrestamoEjemplarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/modificarPrestamoEj" +
            "emplarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/modificarPrestamoEj" +
            "emplarResponse")]
        System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.modificarPrestamoEjemplarResponse> modificarPrestamoEjemplarAsync(FrontEnd.PrestamoEjemplarWS.modificarPrestamoEjemplarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosSoli" +
            "citadosRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosSoli" +
            "citadosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.PrestamoEjemplarWS.listarPrestamosSolicitadosResponse listarPrestamosSolicitados(FrontEnd.PrestamoEjemplarWS.listarPrestamosSolicitadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosSoli" +
            "citadosRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosSoli" +
            "citadosResponse")]
        System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.listarPrestamosSolicitadosResponse> listarPrestamosSolicitadosAsync(FrontEnd.PrestamoEjemplarWS.listarPrestamosSolicitadosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/eliminarPrestamoEje" +
            "mplarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/eliminarPrestamoEje" +
            "mplarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.PrestamoEjemplarWS.eliminarPrestamoEjemplarResponse eliminarPrestamoEjemplar(FrontEnd.PrestamoEjemplarWS.eliminarPrestamoEjemplarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/eliminarPrestamoEje" +
            "mplarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/eliminarPrestamoEje" +
            "mplarResponse")]
        System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.eliminarPrestamoEjemplarResponse> eliminarPrestamoEjemplarAsync(FrontEnd.PrestamoEjemplarWS.eliminarPrestamoEjemplarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosNoCu" +
            "lminadosRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosNoCu" +
            "lminadosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.PrestamoEjemplarWS.listarPrestamosNoCulminadosResponse listarPrestamosNoCulminados(FrontEnd.PrestamoEjemplarWS.listarPrestamosNoCulminadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosNoCu" +
            "lminadosRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarPrestamosNoCu" +
            "lminadosResponse")]
        System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.listarPrestamosNoCulminadosResponse> listarPrestamosNoCulminadosAsync(FrontEnd.PrestamoEjemplarWS.listarPrestamosNoCulminadosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/obtenerPrestamoEjem" +
            "plarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/obtenerPrestamoEjem" +
            "plarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.PrestamoEjemplarWS.obtenerPrestamoEjemplarResponse obtenerPrestamoEjemplar(FrontEnd.PrestamoEjemplarWS.obtenerPrestamoEjemplarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/obtenerPrestamoEjem" +
            "plarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/obtenerPrestamoEjem" +
            "plarResponse")]
        System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.obtenerPrestamoEjemplarResponse> obtenerPrestamoEjemplarAsync(FrontEnd.PrestamoEjemplarWS.obtenerPrestamoEjemplarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarTodosPrestamo" +
            "EjemplarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarTodosPrestamo" +
            "EjemplarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.PrestamoEjemplarWS.listarTodosPrestamoEjemplarResponse listarTodosPrestamoEjemplar(FrontEnd.PrestamoEjemplarWS.listarTodosPrestamoEjemplarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarTodosPrestamo" +
            "EjemplarRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/PrestamoEjemplarWS/listarTodosPrestamo" +
            "EjemplarResponse")]
        System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.listarTodosPrestamoEjemplarResponse> listarTodosPrestamoEjemplarAsync(FrontEnd.PrestamoEjemplarWS.listarTodosPrestamoEjemplarRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class prestamosDeEjemplaresDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private estadoPrestamoEjemplar estadoField;
        
        private bool estadoFieldSpecified;
        
        private System.DateTime fechaRealDevolucionField;
        
        private bool fechaRealDevolucionFieldSpecified;
        
        private int idEjemplarField;
        
        private bool idEjemplarFieldSpecified;
        
        private int idPrestamoField;
        
        private bool idPrestamoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public estadoPrestamoEjemplar estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaRealDevolucion {
            get {
                return this.fechaRealDevolucionField;
            }
            set {
                this.fechaRealDevolucionField = value;
                this.RaisePropertyChanged("fechaRealDevolucion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRealDevolucionSpecified {
            get {
                return this.fechaRealDevolucionFieldSpecified;
            }
            set {
                this.fechaRealDevolucionFieldSpecified = value;
                this.RaisePropertyChanged("fechaRealDevolucionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idEjemplar {
            get {
                return this.idEjemplarField;
            }
            set {
                this.idEjemplarField = value;
                this.RaisePropertyChanged("idEjemplar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEjemplarSpecified {
            get {
                return this.idEjemplarFieldSpecified;
            }
            set {
                this.idEjemplarFieldSpecified = value;
                this.RaisePropertyChanged("idEjemplarSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idPrestamo {
            get {
                return this.idPrestamoField;
            }
            set {
                this.idPrestamoField = value;
                this.RaisePropertyChanged("idPrestamo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPrestamoSpecified {
            get {
                return this.idPrestamoFieldSpecified;
            }
            set {
                this.idPrestamoFieldSpecified = value;
                this.RaisePropertyChanged("idPrestamoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public enum estadoPrestamoEjemplar {
        
        /// <remarks/>
        SOLICITADO,
        
        /// <remarks/>
        PRESTADO,
        
        /// <remarks/>
        DEVUELTO,
        
        /// <remarks/>
        ATRASADO,
        
        /// <remarks/>
        NO_RECOGIDO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPrestamoEjemplar", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class insertarPrestamoEjemplarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPestamo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEjemplar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO dto;
        
        public insertarPrestamoEjemplarRequest() {
        }
        
        public insertarPrestamoEjemplarRequest(int idPestamo, int idEjemplar, FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO dto) {
            this.idPestamo = idPestamo;
            this.idEjemplar = idEjemplar;
            this.dto = dto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPrestamoEjemplarResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class insertarPrestamoEjemplarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarPrestamoEjemplarResponse() {
        }
        
        public insertarPrestamoEjemplarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPrestamosDevueltos", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarPrestamosDevueltosRequest {
        
        public listarPrestamosDevueltosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPrestamosDevueltosResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarPrestamosDevueltosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO[] @return;
        
        public listarPrestamosDevueltosResponse() {
        }
        
        public listarPrestamosDevueltosResponse(FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPrestamosAtrasados", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarPrestamosAtrasadosRequest {
        
        public listarPrestamosAtrasadosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPrestamosAtrasadosResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarPrestamosAtrasadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO[] @return;
        
        public listarPrestamosAtrasadosResponse() {
        }
        
        public listarPrestamosAtrasadosResponse(FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPrestamoEjemplar", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class modificarPrestamoEjemplarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO dto;
        
        public modificarPrestamoEjemplarRequest() {
        }
        
        public modificarPrestamoEjemplarRequest(FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO dto) {
            this.dto = dto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPrestamoEjemplarResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class modificarPrestamoEjemplarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarPrestamoEjemplarResponse() {
        }
        
        public modificarPrestamoEjemplarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPrestamosSolicitados", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarPrestamosSolicitadosRequest {
        
        public listarPrestamosSolicitadosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPrestamosSolicitadosResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarPrestamosSolicitadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO[] @return;
        
        public listarPrestamosSolicitadosResponse() {
        }
        
        public listarPrestamosSolicitadosResponse(FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPrestamoEjemplar", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class eliminarPrestamoEjemplarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPrestamo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEjemplar;
        
        public eliminarPrestamoEjemplarRequest() {
        }
        
        public eliminarPrestamoEjemplarRequest(int idPrestamo, int idEjemplar) {
            this.idPrestamo = idPrestamo;
            this.idEjemplar = idEjemplar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPrestamoEjemplarResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class eliminarPrestamoEjemplarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarPrestamoEjemplarResponse() {
        }
        
        public eliminarPrestamoEjemplarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPrestamosNoCulminados", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarPrestamosNoCulminadosRequest {
        
        public listarPrestamosNoCulminadosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPrestamosNoCulminadosResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarPrestamosNoCulminadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO[] @return;
        
        public listarPrestamosNoCulminadosResponse() {
        }
        
        public listarPrestamosNoCulminadosResponse(FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPrestamoEjemplar", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class obtenerPrestamoEjemplarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPrestamo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEjemplar;
        
        public obtenerPrestamoEjemplarRequest() {
        }
        
        public obtenerPrestamoEjemplarRequest(int idPrestamo, int idEjemplar) {
            this.idPrestamo = idPrestamo;
            this.idEjemplar = idEjemplar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPrestamoEjemplarResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class obtenerPrestamoEjemplarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO @return;
        
        public obtenerPrestamoEjemplarResponse() {
        }
        
        public obtenerPrestamoEjemplarResponse(FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosPrestamoEjemplar", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarTodosPrestamoEjemplarRequest {
        
        public listarTodosPrestamoEjemplarRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosPrestamoEjemplarResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarTodosPrestamoEjemplarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO[] @return;
        
        public listarTodosPrestamoEjemplarResponse() {
        }
        
        public listarTodosPrestamoEjemplarResponse(FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PrestamoEjemplarWSChannel : FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrestamoEjemplarWSClient : System.ServiceModel.ClientBase<FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS>, FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS {
        
        public PrestamoEjemplarWSClient() {
        }
        
        public PrestamoEjemplarWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrestamoEjemplarWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrestamoEjemplarWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrestamoEjemplarWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.PrestamoEjemplarWS.insertarPrestamoEjemplarResponse FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS.insertarPrestamoEjemplar(FrontEnd.PrestamoEjemplarWS.insertarPrestamoEjemplarRequest request) {
            return base.Channel.insertarPrestamoEjemplar(request);
        }
        
        public int insertarPrestamoEjemplar(int idPestamo, int idEjemplar, FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO dto) {
            FrontEnd.PrestamoEjemplarWS.insertarPrestamoEjemplarRequest inValue = new FrontEnd.PrestamoEjemplarWS.insertarPrestamoEjemplarRequest();
            inValue.idPestamo = idPestamo;
            inValue.idEjemplar = idEjemplar;
            inValue.dto = dto;
            FrontEnd.PrestamoEjemplarWS.insertarPrestamoEjemplarResponse retVal = ((FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).insertarPrestamoEjemplar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.insertarPrestamoEjemplarResponse> FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS.insertarPrestamoEjemplarAsync(FrontEnd.PrestamoEjemplarWS.insertarPrestamoEjemplarRequest request) {
            return base.Channel.insertarPrestamoEjemplarAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.insertarPrestamoEjemplarResponse> insertarPrestamoEjemplarAsync(int idPestamo, int idEjemplar, FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO dto) {
            FrontEnd.PrestamoEjemplarWS.insertarPrestamoEjemplarRequest inValue = new FrontEnd.PrestamoEjemplarWS.insertarPrestamoEjemplarRequest();
            inValue.idPestamo = idPestamo;
            inValue.idEjemplar = idEjemplar;
            inValue.dto = dto;
            return ((FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).insertarPrestamoEjemplarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.PrestamoEjemplarWS.listarPrestamosDevueltosResponse FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS.listarPrestamosDevueltos(FrontEnd.PrestamoEjemplarWS.listarPrestamosDevueltosRequest request) {
            return base.Channel.listarPrestamosDevueltos(request);
        }
        
        public FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO[] listarPrestamosDevueltos() {
            FrontEnd.PrestamoEjemplarWS.listarPrestamosDevueltosRequest inValue = new FrontEnd.PrestamoEjemplarWS.listarPrestamosDevueltosRequest();
            FrontEnd.PrestamoEjemplarWS.listarPrestamosDevueltosResponse retVal = ((FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).listarPrestamosDevueltos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.listarPrestamosDevueltosResponse> FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS.listarPrestamosDevueltosAsync(FrontEnd.PrestamoEjemplarWS.listarPrestamosDevueltosRequest request) {
            return base.Channel.listarPrestamosDevueltosAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.listarPrestamosDevueltosResponse> listarPrestamosDevueltosAsync() {
            FrontEnd.PrestamoEjemplarWS.listarPrestamosDevueltosRequest inValue = new FrontEnd.PrestamoEjemplarWS.listarPrestamosDevueltosRequest();
            return ((FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).listarPrestamosDevueltosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.PrestamoEjemplarWS.listarPrestamosAtrasadosResponse FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS.listarPrestamosAtrasados(FrontEnd.PrestamoEjemplarWS.listarPrestamosAtrasadosRequest request) {
            return base.Channel.listarPrestamosAtrasados(request);
        }
        
        public FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO[] listarPrestamosAtrasados() {
            FrontEnd.PrestamoEjemplarWS.listarPrestamosAtrasadosRequest inValue = new FrontEnd.PrestamoEjemplarWS.listarPrestamosAtrasadosRequest();
            FrontEnd.PrestamoEjemplarWS.listarPrestamosAtrasadosResponse retVal = ((FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).listarPrestamosAtrasados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.listarPrestamosAtrasadosResponse> FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS.listarPrestamosAtrasadosAsync(FrontEnd.PrestamoEjemplarWS.listarPrestamosAtrasadosRequest request) {
            return base.Channel.listarPrestamosAtrasadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.listarPrestamosAtrasadosResponse> listarPrestamosAtrasadosAsync() {
            FrontEnd.PrestamoEjemplarWS.listarPrestamosAtrasadosRequest inValue = new FrontEnd.PrestamoEjemplarWS.listarPrestamosAtrasadosRequest();
            return ((FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).listarPrestamosAtrasadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.PrestamoEjemplarWS.modificarPrestamoEjemplarResponse FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS.modificarPrestamoEjemplar(FrontEnd.PrestamoEjemplarWS.modificarPrestamoEjemplarRequest request) {
            return base.Channel.modificarPrestamoEjemplar(request);
        }
        
        public int modificarPrestamoEjemplar(FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO dto) {
            FrontEnd.PrestamoEjemplarWS.modificarPrestamoEjemplarRequest inValue = new FrontEnd.PrestamoEjemplarWS.modificarPrestamoEjemplarRequest();
            inValue.dto = dto;
            FrontEnd.PrestamoEjemplarWS.modificarPrestamoEjemplarResponse retVal = ((FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).modificarPrestamoEjemplar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.modificarPrestamoEjemplarResponse> FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS.modificarPrestamoEjemplarAsync(FrontEnd.PrestamoEjemplarWS.modificarPrestamoEjemplarRequest request) {
            return base.Channel.modificarPrestamoEjemplarAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.modificarPrestamoEjemplarResponse> modificarPrestamoEjemplarAsync(FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO dto) {
            FrontEnd.PrestamoEjemplarWS.modificarPrestamoEjemplarRequest inValue = new FrontEnd.PrestamoEjemplarWS.modificarPrestamoEjemplarRequest();
            inValue.dto = dto;
            return ((FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).modificarPrestamoEjemplarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.PrestamoEjemplarWS.listarPrestamosSolicitadosResponse FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS.listarPrestamosSolicitados(FrontEnd.PrestamoEjemplarWS.listarPrestamosSolicitadosRequest request) {
            return base.Channel.listarPrestamosSolicitados(request);
        }
        
        public FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO[] listarPrestamosSolicitados() {
            FrontEnd.PrestamoEjemplarWS.listarPrestamosSolicitadosRequest inValue = new FrontEnd.PrestamoEjemplarWS.listarPrestamosSolicitadosRequest();
            FrontEnd.PrestamoEjemplarWS.listarPrestamosSolicitadosResponse retVal = ((FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).listarPrestamosSolicitados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.listarPrestamosSolicitadosResponse> FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS.listarPrestamosSolicitadosAsync(FrontEnd.PrestamoEjemplarWS.listarPrestamosSolicitadosRequest request) {
            return base.Channel.listarPrestamosSolicitadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.listarPrestamosSolicitadosResponse> listarPrestamosSolicitadosAsync() {
            FrontEnd.PrestamoEjemplarWS.listarPrestamosSolicitadosRequest inValue = new FrontEnd.PrestamoEjemplarWS.listarPrestamosSolicitadosRequest();
            return ((FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).listarPrestamosSolicitadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.PrestamoEjemplarWS.eliminarPrestamoEjemplarResponse FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS.eliminarPrestamoEjemplar(FrontEnd.PrestamoEjemplarWS.eliminarPrestamoEjemplarRequest request) {
            return base.Channel.eliminarPrestamoEjemplar(request);
        }
        
        public int eliminarPrestamoEjemplar(int idPrestamo, int idEjemplar) {
            FrontEnd.PrestamoEjemplarWS.eliminarPrestamoEjemplarRequest inValue = new FrontEnd.PrestamoEjemplarWS.eliminarPrestamoEjemplarRequest();
            inValue.idPrestamo = idPrestamo;
            inValue.idEjemplar = idEjemplar;
            FrontEnd.PrestamoEjemplarWS.eliminarPrestamoEjemplarResponse retVal = ((FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).eliminarPrestamoEjemplar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.eliminarPrestamoEjemplarResponse> FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS.eliminarPrestamoEjemplarAsync(FrontEnd.PrestamoEjemplarWS.eliminarPrestamoEjemplarRequest request) {
            return base.Channel.eliminarPrestamoEjemplarAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.eliminarPrestamoEjemplarResponse> eliminarPrestamoEjemplarAsync(int idPrestamo, int idEjemplar) {
            FrontEnd.PrestamoEjemplarWS.eliminarPrestamoEjemplarRequest inValue = new FrontEnd.PrestamoEjemplarWS.eliminarPrestamoEjemplarRequest();
            inValue.idPrestamo = idPrestamo;
            inValue.idEjemplar = idEjemplar;
            return ((FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).eliminarPrestamoEjemplarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.PrestamoEjemplarWS.listarPrestamosNoCulminadosResponse FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS.listarPrestamosNoCulminados(FrontEnd.PrestamoEjemplarWS.listarPrestamosNoCulminadosRequest request) {
            return base.Channel.listarPrestamosNoCulminados(request);
        }
        
        public FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO[] listarPrestamosNoCulminados() {
            FrontEnd.PrestamoEjemplarWS.listarPrestamosNoCulminadosRequest inValue = new FrontEnd.PrestamoEjemplarWS.listarPrestamosNoCulminadosRequest();
            FrontEnd.PrestamoEjemplarWS.listarPrestamosNoCulminadosResponse retVal = ((FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).listarPrestamosNoCulminados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.listarPrestamosNoCulminadosResponse> FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS.listarPrestamosNoCulminadosAsync(FrontEnd.PrestamoEjemplarWS.listarPrestamosNoCulminadosRequest request) {
            return base.Channel.listarPrestamosNoCulminadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.listarPrestamosNoCulminadosResponse> listarPrestamosNoCulminadosAsync() {
            FrontEnd.PrestamoEjemplarWS.listarPrestamosNoCulminadosRequest inValue = new FrontEnd.PrestamoEjemplarWS.listarPrestamosNoCulminadosRequest();
            return ((FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).listarPrestamosNoCulminadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.PrestamoEjemplarWS.obtenerPrestamoEjemplarResponse FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS.obtenerPrestamoEjemplar(FrontEnd.PrestamoEjemplarWS.obtenerPrestamoEjemplarRequest request) {
            return base.Channel.obtenerPrestamoEjemplar(request);
        }
        
        public FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO obtenerPrestamoEjemplar(int idPrestamo, int idEjemplar) {
            FrontEnd.PrestamoEjemplarWS.obtenerPrestamoEjemplarRequest inValue = new FrontEnd.PrestamoEjemplarWS.obtenerPrestamoEjemplarRequest();
            inValue.idPrestamo = idPrestamo;
            inValue.idEjemplar = idEjemplar;
            FrontEnd.PrestamoEjemplarWS.obtenerPrestamoEjemplarResponse retVal = ((FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).obtenerPrestamoEjemplar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.obtenerPrestamoEjemplarResponse> FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS.obtenerPrestamoEjemplarAsync(FrontEnd.PrestamoEjemplarWS.obtenerPrestamoEjemplarRequest request) {
            return base.Channel.obtenerPrestamoEjemplarAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.obtenerPrestamoEjemplarResponse> obtenerPrestamoEjemplarAsync(int idPrestamo, int idEjemplar) {
            FrontEnd.PrestamoEjemplarWS.obtenerPrestamoEjemplarRequest inValue = new FrontEnd.PrestamoEjemplarWS.obtenerPrestamoEjemplarRequest();
            inValue.idPrestamo = idPrestamo;
            inValue.idEjemplar = idEjemplar;
            return ((FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).obtenerPrestamoEjemplarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.PrestamoEjemplarWS.listarTodosPrestamoEjemplarResponse FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS.listarTodosPrestamoEjemplar(FrontEnd.PrestamoEjemplarWS.listarTodosPrestamoEjemplarRequest request) {
            return base.Channel.listarTodosPrestamoEjemplar(request);
        }
        
        public FrontEnd.PrestamoEjemplarWS.prestamosDeEjemplaresDTO[] listarTodosPrestamoEjemplar() {
            FrontEnd.PrestamoEjemplarWS.listarTodosPrestamoEjemplarRequest inValue = new FrontEnd.PrestamoEjemplarWS.listarTodosPrestamoEjemplarRequest();
            FrontEnd.PrestamoEjemplarWS.listarTodosPrestamoEjemplarResponse retVal = ((FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).listarTodosPrestamoEjemplar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.listarTodosPrestamoEjemplarResponse> FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS.listarTodosPrestamoEjemplarAsync(FrontEnd.PrestamoEjemplarWS.listarTodosPrestamoEjemplarRequest request) {
            return base.Channel.listarTodosPrestamoEjemplarAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.PrestamoEjemplarWS.listarTodosPrestamoEjemplarResponse> listarTodosPrestamoEjemplarAsync() {
            FrontEnd.PrestamoEjemplarWS.listarTodosPrestamoEjemplarRequest inValue = new FrontEnd.PrestamoEjemplarWS.listarTodosPrestamoEjemplarRequest();
            return ((FrontEnd.PrestamoEjemplarWS.PrestamoEjemplarWS)(this)).listarTodosPrestamoEjemplarAsync(inValue);
        }
    }
}
