//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.NivelInglesWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", ConfigurationName="NivelInglesWS.NivelInglesWS")]
    public interface NivelInglesWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/NivelInglesWS/insertarNivelRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/NivelInglesWS/insertarNivelResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.NivelInglesWS.insertarNivelResponse insertarNivel(FrontEnd.NivelInglesWS.insertarNivelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/NivelInglesWS/insertarNivelRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/NivelInglesWS/insertarNivelResponse")]
        System.Threading.Tasks.Task<FrontEnd.NivelInglesWS.insertarNivelResponse> insertarNivelAsync(FrontEnd.NivelInglesWS.insertarNivelRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/NivelInglesWS/eliminarNivelRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/NivelInglesWS/eliminarNivelResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.NivelInglesWS.eliminarNivelResponse eliminarNivel(FrontEnd.NivelInglesWS.eliminarNivelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/NivelInglesWS/eliminarNivelRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/NivelInglesWS/eliminarNivelResponse")]
        System.Threading.Tasks.Task<FrontEnd.NivelInglesWS.eliminarNivelResponse> eliminarNivelAsync(FrontEnd.NivelInglesWS.eliminarNivelRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/NivelInglesWS/modificarNivelRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/NivelInglesWS/modificarNivelResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.NivelInglesWS.modificarNivelResponse modificarNivel(FrontEnd.NivelInglesWS.modificarNivelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/NivelInglesWS/modificarNivelRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/NivelInglesWS/modificarNivelResponse")]
        System.Threading.Tasks.Task<FrontEnd.NivelInglesWS.modificarNivelResponse> modificarNivelAsync(FrontEnd.NivelInglesWS.modificarNivelRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/NivelInglesWS/listarNivelesRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/NivelInglesWS/listarNivelesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.NivelInglesWS.listarNivelesResponse listarNiveles(FrontEnd.NivelInglesWS.listarNivelesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/NivelInglesWS/listarNivelesRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/NivelInglesWS/listarNivelesResponse")]
        System.Threading.Tasks.Task<FrontEnd.NivelInglesWS.listarNivelesResponse> listarNivelesAsync(FrontEnd.NivelInglesWS.listarNivelesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/NivelInglesWS/obtenerNivelPorIdRequest" +
            "", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/NivelInglesWS/obtenerNivelPorIdRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.NivelInglesWS.obtenerNivelPorIdResponse obtenerNivelPorId(FrontEnd.NivelInglesWS.obtenerNivelPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/NivelInglesWS/obtenerNivelPorIdRequest" +
            "", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/NivelInglesWS/obtenerNivelPorIdRespons" +
            "e")]
        System.Threading.Tasks.Task<FrontEnd.NivelInglesWS.obtenerNivelPorIdResponse> obtenerNivelPorIdAsync(FrontEnd.NivelInglesWS.obtenerNivelPorIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarNivel", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class insertarNivelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreNivel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        public insertarNivelRequest() {
        }
        
        public insertarNivelRequest(string nombreNivel, string descripcion) {
            this.nombreNivel = nombreNivel;
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarNivelResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class insertarNivelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarNivelResponse() {
        }
        
        public insertarNivelResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarNivel", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class eliminarNivelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idNivel;
        
        public eliminarNivelRequest() {
        }
        
        public eliminarNivelRequest(int idNivel) {
            this.idNivel = idNivel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarNivelResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class eliminarNivelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarNivelResponse() {
        }
        
        public eliminarNivelResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarNivel", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class modificarNivelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idNivel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreNivel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        public modificarNivelRequest() {
        }
        
        public modificarNivelRequest(int idNivel, string nombreNivel, string descripcion) {
            this.idNivel = idNivel;
            this.nombreNivel = nombreNivel;
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarNivelResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class modificarNivelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarNivelResponse() {
        }
        
        public modificarNivelResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class nivelesInglesDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idNivelField;
        
        private nivel nivelField;
        
        private bool nivelFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idNivel {
            get {
                return this.idNivelField;
            }
            set {
                this.idNivelField = value;
                this.RaisePropertyChanged("idNivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public nivel nivel {
            get {
                return this.nivelField;
            }
            set {
                this.nivelField = value;
                this.RaisePropertyChanged("nivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nivelSpecified {
            get {
                return this.nivelFieldSpecified;
            }
            set {
                this.nivelFieldSpecified = value;
                this.RaisePropertyChanged("nivelSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public enum nivel {
        
        /// <remarks/>
        BASICO,
        
        /// <remarks/>
        INTERMEDIO,
        
        /// <remarks/>
        AVANZADO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarNiveles", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarNivelesRequest {
        
        public listarNivelesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarNivelesResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarNivelesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontEnd.NivelInglesWS.nivelesInglesDTO[] @return;
        
        public listarNivelesResponse() {
        }
        
        public listarNivelesResponse(FrontEnd.NivelInglesWS.nivelesInglesDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerNivelPorId", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class obtenerNivelPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idNivel;
        
        public obtenerNivelPorIdRequest() {
        }
        
        public obtenerNivelPorIdRequest(int idNivel) {
            this.idNivel = idNivel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerNivelPorIdResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class obtenerNivelPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontEnd.NivelInglesWS.nivelesInglesDTO @return;
        
        public obtenerNivelPorIdResponse() {
        }
        
        public obtenerNivelPorIdResponse(FrontEnd.NivelInglesWS.nivelesInglesDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NivelInglesWSChannel : FrontEnd.NivelInglesWS.NivelInglesWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NivelInglesWSClient : System.ServiceModel.ClientBase<FrontEnd.NivelInglesWS.NivelInglesWS>, FrontEnd.NivelInglesWS.NivelInglesWS {
        
        public NivelInglesWSClient() {
        }
        
        public NivelInglesWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NivelInglesWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NivelInglesWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NivelInglesWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.NivelInglesWS.insertarNivelResponse FrontEnd.NivelInglesWS.NivelInglesWS.insertarNivel(FrontEnd.NivelInglesWS.insertarNivelRequest request) {
            return base.Channel.insertarNivel(request);
        }
        
        public int insertarNivel(string nombreNivel, string descripcion) {
            FrontEnd.NivelInglesWS.insertarNivelRequest inValue = new FrontEnd.NivelInglesWS.insertarNivelRequest();
            inValue.nombreNivel = nombreNivel;
            inValue.descripcion = descripcion;
            FrontEnd.NivelInglesWS.insertarNivelResponse retVal = ((FrontEnd.NivelInglesWS.NivelInglesWS)(this)).insertarNivel(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.NivelInglesWS.insertarNivelResponse> FrontEnd.NivelInglesWS.NivelInglesWS.insertarNivelAsync(FrontEnd.NivelInglesWS.insertarNivelRequest request) {
            return base.Channel.insertarNivelAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.NivelInglesWS.insertarNivelResponse> insertarNivelAsync(string nombreNivel, string descripcion) {
            FrontEnd.NivelInglesWS.insertarNivelRequest inValue = new FrontEnd.NivelInglesWS.insertarNivelRequest();
            inValue.nombreNivel = nombreNivel;
            inValue.descripcion = descripcion;
            return ((FrontEnd.NivelInglesWS.NivelInglesWS)(this)).insertarNivelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.NivelInglesWS.eliminarNivelResponse FrontEnd.NivelInglesWS.NivelInglesWS.eliminarNivel(FrontEnd.NivelInglesWS.eliminarNivelRequest request) {
            return base.Channel.eliminarNivel(request);
        }
        
        public int eliminarNivel(int idNivel) {
            FrontEnd.NivelInglesWS.eliminarNivelRequest inValue = new FrontEnd.NivelInglesWS.eliminarNivelRequest();
            inValue.idNivel = idNivel;
            FrontEnd.NivelInglesWS.eliminarNivelResponse retVal = ((FrontEnd.NivelInglesWS.NivelInglesWS)(this)).eliminarNivel(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.NivelInglesWS.eliminarNivelResponse> FrontEnd.NivelInglesWS.NivelInglesWS.eliminarNivelAsync(FrontEnd.NivelInglesWS.eliminarNivelRequest request) {
            return base.Channel.eliminarNivelAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.NivelInglesWS.eliminarNivelResponse> eliminarNivelAsync(int idNivel) {
            FrontEnd.NivelInglesWS.eliminarNivelRequest inValue = new FrontEnd.NivelInglesWS.eliminarNivelRequest();
            inValue.idNivel = idNivel;
            return ((FrontEnd.NivelInglesWS.NivelInglesWS)(this)).eliminarNivelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.NivelInglesWS.modificarNivelResponse FrontEnd.NivelInglesWS.NivelInglesWS.modificarNivel(FrontEnd.NivelInglesWS.modificarNivelRequest request) {
            return base.Channel.modificarNivel(request);
        }
        
        public int modificarNivel(int idNivel, string nombreNivel, string descripcion) {
            FrontEnd.NivelInglesWS.modificarNivelRequest inValue = new FrontEnd.NivelInglesWS.modificarNivelRequest();
            inValue.idNivel = idNivel;
            inValue.nombreNivel = nombreNivel;
            inValue.descripcion = descripcion;
            FrontEnd.NivelInglesWS.modificarNivelResponse retVal = ((FrontEnd.NivelInglesWS.NivelInglesWS)(this)).modificarNivel(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.NivelInglesWS.modificarNivelResponse> FrontEnd.NivelInglesWS.NivelInglesWS.modificarNivelAsync(FrontEnd.NivelInglesWS.modificarNivelRequest request) {
            return base.Channel.modificarNivelAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.NivelInglesWS.modificarNivelResponse> modificarNivelAsync(int idNivel, string nombreNivel, string descripcion) {
            FrontEnd.NivelInglesWS.modificarNivelRequest inValue = new FrontEnd.NivelInglesWS.modificarNivelRequest();
            inValue.idNivel = idNivel;
            inValue.nombreNivel = nombreNivel;
            inValue.descripcion = descripcion;
            return ((FrontEnd.NivelInglesWS.NivelInglesWS)(this)).modificarNivelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.NivelInglesWS.listarNivelesResponse FrontEnd.NivelInglesWS.NivelInglesWS.listarNiveles(FrontEnd.NivelInglesWS.listarNivelesRequest request) {
            return base.Channel.listarNiveles(request);
        }
        
        public FrontEnd.NivelInglesWS.nivelesInglesDTO[] listarNiveles() {
            FrontEnd.NivelInglesWS.listarNivelesRequest inValue = new FrontEnd.NivelInglesWS.listarNivelesRequest();
            FrontEnd.NivelInglesWS.listarNivelesResponse retVal = ((FrontEnd.NivelInglesWS.NivelInglesWS)(this)).listarNiveles(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.NivelInglesWS.listarNivelesResponse> FrontEnd.NivelInglesWS.NivelInglesWS.listarNivelesAsync(FrontEnd.NivelInglesWS.listarNivelesRequest request) {
            return base.Channel.listarNivelesAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.NivelInglesWS.listarNivelesResponse> listarNivelesAsync() {
            FrontEnd.NivelInglesWS.listarNivelesRequest inValue = new FrontEnd.NivelInglesWS.listarNivelesRequest();
            return ((FrontEnd.NivelInglesWS.NivelInglesWS)(this)).listarNivelesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.NivelInglesWS.obtenerNivelPorIdResponse FrontEnd.NivelInglesWS.NivelInglesWS.obtenerNivelPorId(FrontEnd.NivelInglesWS.obtenerNivelPorIdRequest request) {
            return base.Channel.obtenerNivelPorId(request);
        }
        
        public FrontEnd.NivelInglesWS.nivelesInglesDTO obtenerNivelPorId(int idNivel) {
            FrontEnd.NivelInglesWS.obtenerNivelPorIdRequest inValue = new FrontEnd.NivelInglesWS.obtenerNivelPorIdRequest();
            inValue.idNivel = idNivel;
            FrontEnd.NivelInglesWS.obtenerNivelPorIdResponse retVal = ((FrontEnd.NivelInglesWS.NivelInglesWS)(this)).obtenerNivelPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.NivelInglesWS.obtenerNivelPorIdResponse> FrontEnd.NivelInglesWS.NivelInglesWS.obtenerNivelPorIdAsync(FrontEnd.NivelInglesWS.obtenerNivelPorIdRequest request) {
            return base.Channel.obtenerNivelPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.NivelInglesWS.obtenerNivelPorIdResponse> obtenerNivelPorIdAsync(int idNivel) {
            FrontEnd.NivelInglesWS.obtenerNivelPorIdRequest inValue = new FrontEnd.NivelInglesWS.obtenerNivelPorIdRequest();
            inValue.idNivel = idNivel;
            return ((FrontEnd.NivelInglesWS.NivelInglesWS)(this)).obtenerNivelPorIdAsync(inValue);
        }
    }
}
