//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.SancionWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", ConfigurationName="SancionWS.SancionWS")]
    public interface SancionWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SancionWS/tieneSancionesActivasRequest" +
            "", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SancionWS/tieneSancionesActivasRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.SancionWS.tieneSancionesActivasResponse tieneSancionesActivas(FrontEnd.SancionWS.tieneSancionesActivasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SancionWS/tieneSancionesActivasRequest" +
            "", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SancionWS/tieneSancionesActivasRespons" +
            "e")]
        System.Threading.Tasks.Task<FrontEnd.SancionWS.tieneSancionesActivasResponse> tieneSancionesActivasAsync(FrontEnd.SancionWS.tieneSancionesActivasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SancionWS/listarSancionesPorPersonaReq" +
            "uest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SancionWS/listarSancionesPorPersonaRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.SancionWS.listarSancionesPorPersonaResponse listarSancionesPorPersona(FrontEnd.SancionWS.listarSancionesPorPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SancionWS/listarSancionesPorPersonaReq" +
            "uest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SancionWS/listarSancionesPorPersonaRes" +
            "ponse")]
        System.Threading.Tasks.Task<FrontEnd.SancionWS.listarSancionesPorPersonaResponse> listarSancionesPorPersonaAsync(FrontEnd.SancionWS.listarSancionesPorPersonaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SancionWS/obtenerSancionPorIdRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SancionWS/obtenerSancionPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.SancionWS.obtenerSancionPorIdResponse obtenerSancionPorId(FrontEnd.SancionWS.obtenerSancionPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SancionWS/obtenerSancionPorIdRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SancionWS/obtenerSancionPorIdResponse")]
        System.Threading.Tasks.Task<FrontEnd.SancionWS.obtenerSancionPorIdResponse> obtenerSancionPorIdAsync(FrontEnd.SancionWS.obtenerSancionPorIdRequest request);
        
        // CODEGEN: El parámetro 'idPersona' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SancionWS/verificarSancionesActivasReq" +
            "uest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SancionWS/verificarSancionesActivasRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FrontEnd.SancionWS.verificarSancionesActivasResponse verificarSancionesActivas(FrontEnd.SancionWS.verificarSancionesActivasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SancionWS/verificarSancionesActivasReq" +
            "uest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SancionWS/verificarSancionesActivasRes" +
            "ponse")]
        System.Threading.Tasks.Task<FrontEnd.SancionWS.verificarSancionesActivasResponse> verificarSancionesActivasAsync(FrontEnd.SancionWS.verificarSancionesActivasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SancionWS/modificarSancionRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SancionWS/modificarSancionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.SancionWS.modificarSancionResponse modificarSancion(FrontEnd.SancionWS.modificarSancionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SancionWS/modificarSancionRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SancionWS/modificarSancionResponse")]
        System.Threading.Tasks.Task<FrontEnd.SancionWS.modificarSancionResponse> modificarSancionAsync(FrontEnd.SancionWS.modificarSancionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SancionWS/listarSancionesRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SancionWS/listarSancionesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.SancionWS.listarSancionesResponse listarSanciones(FrontEnd.SancionWS.listarSancionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SancionWS/listarSancionesRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SancionWS/listarSancionesResponse")]
        System.Threading.Tasks.Task<FrontEnd.SancionWS.listarSancionesResponse> listarSancionesAsync(FrontEnd.SancionWS.listarSancionesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SancionWS/eliminarSancionRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SancionWS/eliminarSancionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.SancionWS.eliminarSancionResponse eliminarSancion(FrontEnd.SancionWS.eliminarSancionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SancionWS/eliminarSancionRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SancionWS/eliminarSancionResponse")]
        System.Threading.Tasks.Task<FrontEnd.SancionWS.eliminarSancionResponse> eliminarSancionAsync(FrontEnd.SancionWS.eliminarSancionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SancionWS/insertarSancionRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SancionWS/insertarSancionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FrontEnd.SancionWS.insertarSancionResponse insertarSancion(FrontEnd.SancionWS.insertarSancionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bibliows.biblioteca.syntaxerror.com/SancionWS/insertarSancionRequest", ReplyAction="http://bibliows.biblioteca.syntaxerror.com/SancionWS/insertarSancionResponse")]
        System.Threading.Tasks.Task<FrontEnd.SancionWS.insertarSancionResponse> insertarSancionAsync(FrontEnd.SancionWS.insertarSancionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tieneSancionesActivas", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class tieneSancionesActivasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPersona;
        
        public tieneSancionesActivasRequest() {
        }
        
        public tieneSancionesActivasRequest(int idPersona) {
            this.idPersona = idPersona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tieneSancionesActivasResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class tieneSancionesActivasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public tieneSancionesActivasResponse() {
        }
        
        public tieneSancionesActivasResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class sancionesDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private System.DateTime duracionField;
        
        private bool duracionFieldSpecified;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private int idSancionField;
        
        private bool idSancionFieldSpecified;
        
        private double montoField;
        
        private bool montoFieldSpecified;
        
        private prestamosDTO prestamoField;
        
        private tipoSancion tipoField;
        
        private bool tipoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime duracion {
            get {
                return this.duracionField;
            }
            set {
                this.duracionField = value;
                this.RaisePropertyChanged("duracion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool duracionSpecified {
            get {
                return this.duracionFieldSpecified;
            }
            set {
                this.duracionFieldSpecified = value;
                this.RaisePropertyChanged("duracionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idSancion {
            get {
                return this.idSancionField;
            }
            set {
                this.idSancionField = value;
                this.RaisePropertyChanged("idSancion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSancionSpecified {
            get {
                return this.idSancionFieldSpecified;
            }
            set {
                this.idSancionFieldSpecified = value;
                this.RaisePropertyChanged("idSancionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
                this.RaisePropertyChanged("monto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool montoSpecified {
            get {
                return this.montoFieldSpecified;
            }
            set {
                this.montoFieldSpecified = value;
                this.RaisePropertyChanged("montoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public prestamosDTO prestamo {
            get {
                return this.prestamoField;
            }
            set {
                this.prestamoField = value;
                this.RaisePropertyChanged("prestamo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public tipoSancion tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class prestamosDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaDevolucionField;
        
        private bool fechaDevolucionFieldSpecified;
        
        private System.DateTime fechaPrestamoField;
        
        private bool fechaPrestamoFieldSpecified;
        
        private System.DateTime fechaSolicitudField;
        
        private bool fechaSolicitudFieldSpecified;
        
        private int idPrestamoField;
        
        private bool idPrestamoFieldSpecified;
        
        private personasDTO personaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fechaDevolucion {
            get {
                return this.fechaDevolucionField;
            }
            set {
                this.fechaDevolucionField = value;
                this.RaisePropertyChanged("fechaDevolucion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaDevolucionSpecified {
            get {
                return this.fechaDevolucionFieldSpecified;
            }
            set {
                this.fechaDevolucionFieldSpecified = value;
                this.RaisePropertyChanged("fechaDevolucionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaPrestamo {
            get {
                return this.fechaPrestamoField;
            }
            set {
                this.fechaPrestamoField = value;
                this.RaisePropertyChanged("fechaPrestamo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaPrestamoSpecified {
            get {
                return this.fechaPrestamoFieldSpecified;
            }
            set {
                this.fechaPrestamoFieldSpecified = value;
                this.RaisePropertyChanged("fechaPrestamoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaSolicitud {
            get {
                return this.fechaSolicitudField;
            }
            set {
                this.fechaSolicitudField = value;
                this.RaisePropertyChanged("fechaSolicitud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSolicitudSpecified {
            get {
                return this.fechaSolicitudFieldSpecified;
            }
            set {
                this.fechaSolicitudFieldSpecified = value;
                this.RaisePropertyChanged("fechaSolicitudSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idPrestamo {
            get {
                return this.idPrestamoField;
            }
            set {
                this.idPrestamoField = value;
                this.RaisePropertyChanged("idPrestamo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPrestamoSpecified {
            get {
                return this.idPrestamoFieldSpecified;
            }
            set {
                this.idPrestamoFieldSpecified = value;
                this.RaisePropertyChanged("idPrestamoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public personasDTO persona {
            get {
                return this.personaField;
            }
            set {
                this.personaField = value;
                this.RaisePropertyChanged("persona");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class personasDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string contrasenhaField;
        
        private string correoField;
        
        private double deudaField;
        
        private bool deudaFieldSpecified;
        
        private string direccionField;
        
        private System.DateTime fechaContratoFinalField;
        
        private bool fechaContratoFinalFieldSpecified;
        
        private System.DateTime fechaContratoInicioField;
        
        private bool fechaContratoInicioFieldSpecified;
        
        private System.DateTime fechaSancionFinalField;
        
        private bool fechaSancionFinalFieldSpecified;
        
        private int idPersonaField;
        
        private bool idPersonaFieldSpecified;
        
        private string maternoField;
        
        private nivelesInglesDTO nivelField;
        
        private string nombreField;
        
        private string paternoField;
        
        private sedesDTO sedeField;
        
        private string telefonoField;
        
        private tipoPersona tipoField;
        
        private bool tipoFieldSpecified;
        
        private turnos turnoField;
        
        private bool turnoFieldSpecified;
        
        private bool vigenteField;
        
        private bool vigenteFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contrasenha {
            get {
                return this.contrasenhaField;
            }
            set {
                this.contrasenhaField = value;
                this.RaisePropertyChanged("contrasenha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double deuda {
            get {
                return this.deudaField;
            }
            set {
                this.deudaField = value;
                this.RaisePropertyChanged("deuda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deudaSpecified {
            get {
                return this.deudaFieldSpecified;
            }
            set {
                this.deudaFieldSpecified = value;
                this.RaisePropertyChanged("deudaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaContratoFinal {
            get {
                return this.fechaContratoFinalField;
            }
            set {
                this.fechaContratoFinalField = value;
                this.RaisePropertyChanged("fechaContratoFinal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaContratoFinalSpecified {
            get {
                return this.fechaContratoFinalFieldSpecified;
            }
            set {
                this.fechaContratoFinalFieldSpecified = value;
                this.RaisePropertyChanged("fechaContratoFinalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime fechaContratoInicio {
            get {
                return this.fechaContratoInicioField;
            }
            set {
                this.fechaContratoInicioField = value;
                this.RaisePropertyChanged("fechaContratoInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaContratoInicioSpecified {
            get {
                return this.fechaContratoInicioFieldSpecified;
            }
            set {
                this.fechaContratoInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaContratoInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime fechaSancionFinal {
            get {
                return this.fechaSancionFinalField;
            }
            set {
                this.fechaSancionFinalField = value;
                this.RaisePropertyChanged("fechaSancionFinal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSancionFinalSpecified {
            get {
                return this.fechaSancionFinalFieldSpecified;
            }
            set {
                this.fechaSancionFinalFieldSpecified = value;
                this.RaisePropertyChanged("fechaSancionFinalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPersonaSpecified {
            get {
                return this.idPersonaFieldSpecified;
            }
            set {
                this.idPersonaFieldSpecified = value;
                this.RaisePropertyChanged("idPersonaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string materno {
            get {
                return this.maternoField;
            }
            set {
                this.maternoField = value;
                this.RaisePropertyChanged("materno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public nivelesInglesDTO nivel {
            get {
                return this.nivelField;
            }
            set {
                this.nivelField = value;
                this.RaisePropertyChanged("nivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string paterno {
            get {
                return this.paternoField;
            }
            set {
                this.paternoField = value;
                this.RaisePropertyChanged("paterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public sedesDTO sede {
            get {
                return this.sedeField;
            }
            set {
                this.sedeField = value;
                this.RaisePropertyChanged("sede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public tipoPersona tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public turnos turno {
            get {
                return this.turnoField;
            }
            set {
                this.turnoField = value;
                this.RaisePropertyChanged("turno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool turnoSpecified {
            get {
                return this.turnoFieldSpecified;
            }
            set {
                this.turnoFieldSpecified = value;
                this.RaisePropertyChanged("turnoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public bool vigente {
            get {
                return this.vigenteField;
            }
            set {
                this.vigenteField = value;
                this.RaisePropertyChanged("vigente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vigenteSpecified {
            get {
                return this.vigenteFieldSpecified;
            }
            set {
                this.vigenteFieldSpecified = value;
                this.RaisePropertyChanged("vigenteSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class nivelesInglesDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idNivelField;
        
        private nivel nivelField;
        
        private bool nivelFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idNivel {
            get {
                return this.idNivelField;
            }
            set {
                this.idNivelField = value;
                this.RaisePropertyChanged("idNivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public nivel nivel {
            get {
                return this.nivelField;
            }
            set {
                this.nivelField = value;
                this.RaisePropertyChanged("nivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nivelSpecified {
            get {
                return this.nivelFieldSpecified;
            }
            set {
                this.nivelFieldSpecified = value;
                this.RaisePropertyChanged("nivelSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public enum nivel {
        
        /// <remarks/>
        BASICO,
        
        /// <remarks/>
        INTERMEDIO,
        
        /// <remarks/>
        AVANZADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public partial class sedesDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activaField;
        
        private bool activaFieldSpecified;
        
        private string correoContactoField;
        
        private string direccionField;
        
        private string distritoField;
        
        private int idSedeField;
        
        private bool idSedeFieldSpecified;
        
        private string nombreField;
        
        private string telefonoContactoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
                this.RaisePropertyChanged("activa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activaSpecified {
            get {
                return this.activaFieldSpecified;
            }
            set {
                this.activaFieldSpecified = value;
                this.RaisePropertyChanged("activaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correoContacto {
            get {
                return this.correoContactoField;
            }
            set {
                this.correoContactoField = value;
                this.RaisePropertyChanged("correoContacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string distrito {
            get {
                return this.distritoField;
            }
            set {
                this.distritoField = value;
                this.RaisePropertyChanged("distrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idSede {
            get {
                return this.idSedeField;
            }
            set {
                this.idSedeField = value;
                this.RaisePropertyChanged("idSede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSedeSpecified {
            get {
                return this.idSedeFieldSpecified;
            }
            set {
                this.idSedeFieldSpecified = value;
                this.RaisePropertyChanged("idSedeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string telefonoContacto {
            get {
                return this.telefonoContactoField;
            }
            set {
                this.telefonoContactoField = value;
                this.RaisePropertyChanged("telefonoContacto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public enum tipoPersona {
        
        /// <remarks/>
        PROFESOR,
        
        /// <remarks/>
        ADMINISTRADOR,
        
        /// <remarks/>
        ESTUDIANTE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public enum turnos {
        
        /// <remarks/>
        MANHANA,
        
        /// <remarks/>
        TARDE,
        
        /// <remarks/>
        NOCHE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/")]
    public enum tipoSancion {
        
        /// <remarks/>
        DANHO,
        
        /// <remarks/>
        PERDIDA,
        
        /// <remarks/>
        DEMORA,
        
        /// <remarks/>
        EXCEPCION,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarSancionesPorPersona", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarSancionesPorPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPersona;
        
        public listarSancionesPorPersonaRequest() {
        }
        
        public listarSancionesPorPersonaRequest(int idPersona) {
            this.idPersona = idPersona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarSancionesPorPersonaResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarSancionesPorPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontEnd.SancionWS.sancionesDTO[] @return;
        
        public listarSancionesPorPersonaResponse() {
        }
        
        public listarSancionesPorPersonaResponse(FrontEnd.SancionWS.sancionesDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerSancionPorId", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class obtenerSancionPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idSancion;
        
        public obtenerSancionPorIdRequest() {
        }
        
        public obtenerSancionPorIdRequest(int idSancion) {
            this.idSancion = idSancion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerSancionPorIdResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class obtenerSancionPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontEnd.SancionWS.sancionesDTO @return;
        
        public obtenerSancionPorIdResponse() {
        }
        
        public obtenerSancionPorIdResponse(FrontEnd.SancionWS.sancionesDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarSancionesActivas", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class verificarSancionesActivasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPersona;
        
        public verificarSancionesActivasRequest() {
        }
        
        public verificarSancionesActivasRequest(int idPersona) {
            this.idPersona = idPersona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarSancionesActivasResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class verificarSancionesActivasResponse {
        
        public verificarSancionesActivasResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarSancion", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class modificarSancionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idSancion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontEnd.SancionWS.tipoSancion tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double monto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime duracion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPrestamo;
        
        public modificarSancionRequest() {
        }
        
        public modificarSancionRequest(int idSancion, FrontEnd.SancionWS.tipoSancion tipo, System.DateTime fecha, double monto, System.DateTime duracion, string descripcion, int idPrestamo) {
            this.idSancion = idSancion;
            this.tipo = tipo;
            this.fecha = fecha;
            this.monto = monto;
            this.duracion = duracion;
            this.descripcion = descripcion;
            this.idPrestamo = idPrestamo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarSancionResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class modificarSancionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarSancionResponse() {
        }
        
        public modificarSancionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarSanciones", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarSancionesRequest {
        
        public listarSancionesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarSancionesResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class listarSancionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontEnd.SancionWS.sancionesDTO[] @return;
        
        public listarSancionesResponse() {
        }
        
        public listarSancionesResponse(FrontEnd.SancionWS.sancionesDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarSancion", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class eliminarSancionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idSancion;
        
        public eliminarSancionRequest() {
        }
        
        public eliminarSancionRequest(int idSancion) {
            this.idSancion = idSancion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarSancionResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class eliminarSancionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarSancionResponse() {
        }
        
        public eliminarSancionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarSancion", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class insertarSancionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FrontEnd.SancionWS.tipoSancion tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double monto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime duracion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPrestamo;
        
        public insertarSancionRequest() {
        }
        
        public insertarSancionRequest(FrontEnd.SancionWS.tipoSancion tipo, System.DateTime fecha, double monto, System.DateTime duracion, string descripcion, int idPrestamo) {
            this.tipo = tipo;
            this.fecha = fecha;
            this.monto = monto;
            this.duracion = duracion;
            this.descripcion = descripcion;
            this.idPrestamo = idPrestamo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarSancionResponse", WrapperNamespace="http://bibliows.biblioteca.syntaxerror.com/", IsWrapped=true)]
    public partial class insertarSancionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bibliows.biblioteca.syntaxerror.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarSancionResponse() {
        }
        
        public insertarSancionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SancionWSChannel : FrontEnd.SancionWS.SancionWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SancionWSClient : System.ServiceModel.ClientBase<FrontEnd.SancionWS.SancionWS>, FrontEnd.SancionWS.SancionWS {
        
        public SancionWSClient() {
        }
        
        public SancionWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SancionWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SancionWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SancionWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.SancionWS.tieneSancionesActivasResponse FrontEnd.SancionWS.SancionWS.tieneSancionesActivas(FrontEnd.SancionWS.tieneSancionesActivasRequest request) {
            return base.Channel.tieneSancionesActivas(request);
        }
        
        public bool tieneSancionesActivas(int idPersona) {
            FrontEnd.SancionWS.tieneSancionesActivasRequest inValue = new FrontEnd.SancionWS.tieneSancionesActivasRequest();
            inValue.idPersona = idPersona;
            FrontEnd.SancionWS.tieneSancionesActivasResponse retVal = ((FrontEnd.SancionWS.SancionWS)(this)).tieneSancionesActivas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.SancionWS.tieneSancionesActivasResponse> FrontEnd.SancionWS.SancionWS.tieneSancionesActivasAsync(FrontEnd.SancionWS.tieneSancionesActivasRequest request) {
            return base.Channel.tieneSancionesActivasAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.SancionWS.tieneSancionesActivasResponse> tieneSancionesActivasAsync(int idPersona) {
            FrontEnd.SancionWS.tieneSancionesActivasRequest inValue = new FrontEnd.SancionWS.tieneSancionesActivasRequest();
            inValue.idPersona = idPersona;
            return ((FrontEnd.SancionWS.SancionWS)(this)).tieneSancionesActivasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.SancionWS.listarSancionesPorPersonaResponse FrontEnd.SancionWS.SancionWS.listarSancionesPorPersona(FrontEnd.SancionWS.listarSancionesPorPersonaRequest request) {
            return base.Channel.listarSancionesPorPersona(request);
        }
        
        public FrontEnd.SancionWS.sancionesDTO[] listarSancionesPorPersona(int idPersona) {
            FrontEnd.SancionWS.listarSancionesPorPersonaRequest inValue = new FrontEnd.SancionWS.listarSancionesPorPersonaRequest();
            inValue.idPersona = idPersona;
            FrontEnd.SancionWS.listarSancionesPorPersonaResponse retVal = ((FrontEnd.SancionWS.SancionWS)(this)).listarSancionesPorPersona(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.SancionWS.listarSancionesPorPersonaResponse> FrontEnd.SancionWS.SancionWS.listarSancionesPorPersonaAsync(FrontEnd.SancionWS.listarSancionesPorPersonaRequest request) {
            return base.Channel.listarSancionesPorPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.SancionWS.listarSancionesPorPersonaResponse> listarSancionesPorPersonaAsync(int idPersona) {
            FrontEnd.SancionWS.listarSancionesPorPersonaRequest inValue = new FrontEnd.SancionWS.listarSancionesPorPersonaRequest();
            inValue.idPersona = idPersona;
            return ((FrontEnd.SancionWS.SancionWS)(this)).listarSancionesPorPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.SancionWS.obtenerSancionPorIdResponse FrontEnd.SancionWS.SancionWS.obtenerSancionPorId(FrontEnd.SancionWS.obtenerSancionPorIdRequest request) {
            return base.Channel.obtenerSancionPorId(request);
        }
        
        public FrontEnd.SancionWS.sancionesDTO obtenerSancionPorId(int idSancion) {
            FrontEnd.SancionWS.obtenerSancionPorIdRequest inValue = new FrontEnd.SancionWS.obtenerSancionPorIdRequest();
            inValue.idSancion = idSancion;
            FrontEnd.SancionWS.obtenerSancionPorIdResponse retVal = ((FrontEnd.SancionWS.SancionWS)(this)).obtenerSancionPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.SancionWS.obtenerSancionPorIdResponse> FrontEnd.SancionWS.SancionWS.obtenerSancionPorIdAsync(FrontEnd.SancionWS.obtenerSancionPorIdRequest request) {
            return base.Channel.obtenerSancionPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.SancionWS.obtenerSancionPorIdResponse> obtenerSancionPorIdAsync(int idSancion) {
            FrontEnd.SancionWS.obtenerSancionPorIdRequest inValue = new FrontEnd.SancionWS.obtenerSancionPorIdRequest();
            inValue.idSancion = idSancion;
            return ((FrontEnd.SancionWS.SancionWS)(this)).obtenerSancionPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.SancionWS.verificarSancionesActivasResponse FrontEnd.SancionWS.SancionWS.verificarSancionesActivas(FrontEnd.SancionWS.verificarSancionesActivasRequest request) {
            return base.Channel.verificarSancionesActivas(request);
        }
        
        public void verificarSancionesActivas(int idPersona) {
            FrontEnd.SancionWS.verificarSancionesActivasRequest inValue = new FrontEnd.SancionWS.verificarSancionesActivasRequest();
            inValue.idPersona = idPersona;
            FrontEnd.SancionWS.verificarSancionesActivasResponse retVal = ((FrontEnd.SancionWS.SancionWS)(this)).verificarSancionesActivas(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.SancionWS.verificarSancionesActivasResponse> FrontEnd.SancionWS.SancionWS.verificarSancionesActivasAsync(FrontEnd.SancionWS.verificarSancionesActivasRequest request) {
            return base.Channel.verificarSancionesActivasAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.SancionWS.verificarSancionesActivasResponse> verificarSancionesActivasAsync(int idPersona) {
            FrontEnd.SancionWS.verificarSancionesActivasRequest inValue = new FrontEnd.SancionWS.verificarSancionesActivasRequest();
            inValue.idPersona = idPersona;
            return ((FrontEnd.SancionWS.SancionWS)(this)).verificarSancionesActivasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.SancionWS.modificarSancionResponse FrontEnd.SancionWS.SancionWS.modificarSancion(FrontEnd.SancionWS.modificarSancionRequest request) {
            return base.Channel.modificarSancion(request);
        }
        
        public int modificarSancion(int idSancion, FrontEnd.SancionWS.tipoSancion tipo, System.DateTime fecha, double monto, System.DateTime duracion, string descripcion, int idPrestamo) {
            FrontEnd.SancionWS.modificarSancionRequest inValue = new FrontEnd.SancionWS.modificarSancionRequest();
            inValue.idSancion = idSancion;
            inValue.tipo = tipo;
            inValue.fecha = fecha;
            inValue.monto = monto;
            inValue.duracion = duracion;
            inValue.descripcion = descripcion;
            inValue.idPrestamo = idPrestamo;
            FrontEnd.SancionWS.modificarSancionResponse retVal = ((FrontEnd.SancionWS.SancionWS)(this)).modificarSancion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.SancionWS.modificarSancionResponse> FrontEnd.SancionWS.SancionWS.modificarSancionAsync(FrontEnd.SancionWS.modificarSancionRequest request) {
            return base.Channel.modificarSancionAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.SancionWS.modificarSancionResponse> modificarSancionAsync(int idSancion, FrontEnd.SancionWS.tipoSancion tipo, System.DateTime fecha, double monto, System.DateTime duracion, string descripcion, int idPrestamo) {
            FrontEnd.SancionWS.modificarSancionRequest inValue = new FrontEnd.SancionWS.modificarSancionRequest();
            inValue.idSancion = idSancion;
            inValue.tipo = tipo;
            inValue.fecha = fecha;
            inValue.monto = monto;
            inValue.duracion = duracion;
            inValue.descripcion = descripcion;
            inValue.idPrestamo = idPrestamo;
            return ((FrontEnd.SancionWS.SancionWS)(this)).modificarSancionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.SancionWS.listarSancionesResponse FrontEnd.SancionWS.SancionWS.listarSanciones(FrontEnd.SancionWS.listarSancionesRequest request) {
            return base.Channel.listarSanciones(request);
        }
        
        public FrontEnd.SancionWS.sancionesDTO[] listarSanciones() {
            FrontEnd.SancionWS.listarSancionesRequest inValue = new FrontEnd.SancionWS.listarSancionesRequest();
            FrontEnd.SancionWS.listarSancionesResponse retVal = ((FrontEnd.SancionWS.SancionWS)(this)).listarSanciones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.SancionWS.listarSancionesResponse> FrontEnd.SancionWS.SancionWS.listarSancionesAsync(FrontEnd.SancionWS.listarSancionesRequest request) {
            return base.Channel.listarSancionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.SancionWS.listarSancionesResponse> listarSancionesAsync() {
            FrontEnd.SancionWS.listarSancionesRequest inValue = new FrontEnd.SancionWS.listarSancionesRequest();
            return ((FrontEnd.SancionWS.SancionWS)(this)).listarSancionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.SancionWS.eliminarSancionResponse FrontEnd.SancionWS.SancionWS.eliminarSancion(FrontEnd.SancionWS.eliminarSancionRequest request) {
            return base.Channel.eliminarSancion(request);
        }
        
        public int eliminarSancion(int idSancion) {
            FrontEnd.SancionWS.eliminarSancionRequest inValue = new FrontEnd.SancionWS.eliminarSancionRequest();
            inValue.idSancion = idSancion;
            FrontEnd.SancionWS.eliminarSancionResponse retVal = ((FrontEnd.SancionWS.SancionWS)(this)).eliminarSancion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.SancionWS.eliminarSancionResponse> FrontEnd.SancionWS.SancionWS.eliminarSancionAsync(FrontEnd.SancionWS.eliminarSancionRequest request) {
            return base.Channel.eliminarSancionAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.SancionWS.eliminarSancionResponse> eliminarSancionAsync(int idSancion) {
            FrontEnd.SancionWS.eliminarSancionRequest inValue = new FrontEnd.SancionWS.eliminarSancionRequest();
            inValue.idSancion = idSancion;
            return ((FrontEnd.SancionWS.SancionWS)(this)).eliminarSancionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrontEnd.SancionWS.insertarSancionResponse FrontEnd.SancionWS.SancionWS.insertarSancion(FrontEnd.SancionWS.insertarSancionRequest request) {
            return base.Channel.insertarSancion(request);
        }
        
        public int insertarSancion(FrontEnd.SancionWS.tipoSancion tipo, System.DateTime fecha, double monto, System.DateTime duracion, string descripcion, int idPrestamo) {
            FrontEnd.SancionWS.insertarSancionRequest inValue = new FrontEnd.SancionWS.insertarSancionRequest();
            inValue.tipo = tipo;
            inValue.fecha = fecha;
            inValue.monto = monto;
            inValue.duracion = duracion;
            inValue.descripcion = descripcion;
            inValue.idPrestamo = idPrestamo;
            FrontEnd.SancionWS.insertarSancionResponse retVal = ((FrontEnd.SancionWS.SancionWS)(this)).insertarSancion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrontEnd.SancionWS.insertarSancionResponse> FrontEnd.SancionWS.SancionWS.insertarSancionAsync(FrontEnd.SancionWS.insertarSancionRequest request) {
            return base.Channel.insertarSancionAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrontEnd.SancionWS.insertarSancionResponse> insertarSancionAsync(FrontEnd.SancionWS.tipoSancion tipo, System.DateTime fecha, double monto, System.DateTime duracion, string descripcion, int idPrestamo) {
            FrontEnd.SancionWS.insertarSancionRequest inValue = new FrontEnd.SancionWS.insertarSancionRequest();
            inValue.tipo = tipo;
            inValue.fecha = fecha;
            inValue.monto = monto;
            inValue.duracion = duracion;
            inValue.descripcion = descripcion;
            inValue.idPrestamo = idPrestamo;
            return ((FrontEnd.SancionWS.SancionWS)(this)).insertarSancionAsync(inValue);
        }
    }
}
